[tool.poetry]
name = "pythonserver"
version = "0.1.0"
description = ""
authors = ["Lasse <lasseboegeskov@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.12"
uvicorn ="^0.27.1"
fastapi = "^0.109.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
